name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract tag name
        id: extract_tag
        run: echo $(basename $GITHUB_REF) > tag.txt
        
      - name: Read tag name from file
        id: read_tag
        run: echo ::set-output name=TAG_NAME::$(cat tag.txt)
        shell: bash

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/aymengazzah/ansible-runner:${{ steps.read_tag.outputs.TAG_NAME }}
          labels: |
            org.opencontainers.image.source=https://github.com/aymengazzah/ansible-runner
            org.opencontainers.image.description="Ansible-runner"
            org.opencontainers.image.url=https://github.com/aymengazzah/ansible-runner
            org.opencontainers.image.licenses=Apache2.0
            org.opencontainers.image.visibility=public
